// All ability IDs
export const ABILITY_IDS = {
  // Branches
  CREATE_BRANCH: 269,
  UPDATE_BRANCH: 270,
  DELETE_BRANCH: 271,
  VIEW_BRANCHES: 272,

  // Employees
  CREATE_EMPLOYEE: 273,
  UPDATE_EMPLOYEE: 274,
  DELETE_EMPLOYEE: 275,
  VIEW_EMPLOYEES: 276,

  // Clients
  CREATE_CLIENT: 277,
  UPDATE_CLIENT: 278,
  DELETE_CLIENT: 279,
  VIEW_CLIENTS: 280,

  // Services
  CREATE_SERVICE: 281,
  UPDATE_SERVICE: 282,
  DELETE_SERVICE: 283,
  VIEW_SERVICES: 284,

  // Expenses
  CREATE_EXPENSE: 285,
  UPDATE_EXPENSE: 286,
  DELETE_EXPENSE: 287,
  VIEW_EXPENSES: 288,

  // Discounts
  CREATE_DISCOUNT: 289,
  UPDATE_DISCOUNT: 290,
  DELETE_DISCOUNT: 291,
  VIEW_DISCOUNTS: 292,

  // Orders
  CREATE_ORDER: 293,
  UPDATE_ORDER: 294,
  DELETE_ORDER: 295,
  VIEW_ORDERS: 296,

  // Agents
  CREATE_AGENT: 297,
  VIEW_AGENTS: 298,
  UPDATE_AGENT: 299,
  DELETE_AGENT: 300,

  // Reports
  VIEW_EXECUTIVE_REPORT: 301,
  VIEW_DAILY_DETAILS_REPORT: 302,
  VIEW_DAILY_REPORT: 303,

  // Order Logs
  VIEW_PENDING_ORDERS: 304,
  VIEW_NEW_ORDERS: 305,
  VIEW_PENDING_CERTIFICATES: 306,
  VIEW_NEW_CERTIFICATES: 307,
  VIEW_COLLECTED: 308,
  VIEW_IN_PROGRESS: 309,
  VIEW_COMPLETED_ORDERS: 310,
  VIEW_ORDER_RECEIPT: 311,

  // Fulfillment
  VIEW_CLIENT_FULFILLMENT: 312,
  VIEW_FULFILLMENT: 313,
  VIEW_CERTIFICATE_FULFILLMENT: 314,

  // Custody
  MANAGE_CUSTODY: 315,
  VIEW_CUSTODY: 316,

  // Dashboard
  VIEW_DASHBOARD: 317,

  // Commissions
  MANAGE_COMMISSIONS: 318,
  VIEW_COMMISSIONS: 319,

  // Transfers
  VIEW_TRANSFERS: 321,
} as const;

// Check if user has a specific ability
export function can(userAbilities: number[], abilityId: number): boolean {
  return userAbilities.includes(abilityId);
}
