export enum orderStatus {
  WAITING_FOR_DOCUMENTS = 1,
  NEW_ORDER = 2,
  COLLECTED = 3,
  IN_PROGRESS = 4,
  COMPLETED = 5,
  CONTACTED = 6,
  RECEIVED_FROM_CLIENT = 7,
  CANCELLED = 8,
  RETURNED = 9,
  CLIENT_FULFILLMENT = 10,
  SGL_FULFILLMENT = 11,
  CERTIFICATE_FULFILLMENT = 12,
}
